### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

GET localhost:8080/books/monthly

###

GET localhost:8080/books/type/bestseller?page=0&size=10