server:
  port: 8087
  tomcat:
    threads:
      max: 30

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  rabbitmq:
    virtual-host: vh1_prod
  datasource:
    url: jdbc:mysql://133.186.241.167:3306/project_be8_triple_seven_book_coupon?serverTimezone=UTC&characterEncoding=UTF-8
    username: project_be8_triple_seven
    password: eo1cItEUe@J2Tym
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 5           # 초기 커넥션 개수
      max-total: 10             # 최대 커넥션 개수
      min-idle: 2               # 최소 유휴 커넥션 개수
      max-idle: 5               # 최대 유휴 커넥션 개수

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@eureka-server:8761/eureka/
  instance:
    instance-id: book-coupon-api-2
    hostname: localhost
    prefer-ip-address: true