spring:
  profiles:
    active: jhs

  lifecycle:
    timeout-per-shutdown-phase: 30s
  application:
    name: book-coupon-api

  elasticsearch:
    uris: http://115.94.72.197:9200
    username: elastic
    password: nhnacademy123!
    repositories:
      enabled: true

logstash:
  host: 115.94.72.197
  port: 50000 # Logstash TCP input 포트

jasypt:
  encryptor:
    password: nhn24
    algorithm: PBEWithMD5AndDES
    key-obtention-iterations: 1000
    pool-size: 1
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    string-output-type: base64


key:
  manager:
    url: https://api-keymanager.nhncloudservice.com    # Secure Key Manager 엔드포인트
    path: /keymanager/v1.2/appkey/{appKey}/secrets/{keyId}  # 요청 경로
    appKey: qTQNj7LyHhdAazH3                              # NHN Cloud 프로젝트 AppKey
    password: nhn24          # 인증서 비밀번호

database:
    url: 31d0601decaa439ba224aaf4c693663f       # NHN Secure Key Manager에 저장된 Key ID
    user-name: b0994ea9e3174c50ae9a5635fa4277ac
    password: cb7b452b173144a99d217b3869f8017a
    initial-size: 5
    max-total: 10
    min-idle: 2
    max-idle: 5
    max-wait: 1000




#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://admin:1234@eureka-server:8761/eureka
#  instance:
#    prefer-ip-address: true
#
#management:
#  health:
#    status:
#      order: DOWN, UP
#  endpoint:
#    jolokia:
#      enable: true
#    pause:
#      enabled: true
#    resume:
#      enabled: true
#
#  info:
#    env:
#      enabled: true
#
#server:
#  shutdown: graceful
#
##zz


aladin:
  api:
    key: ttbrlgus45311101001





