spring:

  application:
    name: book-coupon-api

  datasource:
    url: jdbc:mysql://133.186.241.167:3306/nhn_academy_37?serverTimezone=UTC&characterEncoding=UTF-8
    username: nhn_academy_37
    password: xo-5vMk2*gQpu*f1
    driver-class-name: com.mysql.cj.jdbc.Driver

#  datasource:
#    url: jdbc:mysql://133.186.241.167:3306/project_be8_triple_seven_book_coupon?serverTimezone=UTC&characterEncoding=UTF-8
#    username: project_be8_triple_seven
#    password: eo1cItEUe@J2Tym
#    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  rabbitmq:
    virtual-host: vh1_dev

logstash:
  host: 115.94.72.197
  port: 50000 # Logstash TCP input 포트

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

aladin:
  api:
    key: ttbrlgus45311101001

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka
  instance:
    instance-id: book-coupon-api
    hostname: localhost
    prefer-ip-address: true

P12_PASSWORD: nhn24

server:
  port: 8086


#??