spring:

  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 10

  lifecycle:
    timeout-per-shutdown-phase: 30s

  application:
    name: book-coupon-api
  cloud:
    loadbalancer:
      retry:
        enabled: true
  profiles:
    active: dev

  elasticsearch:
    uris: http://115.94.72.197:9200
    username: elastic
    password: nhnacademy123!
    repositories:
      enabled: true
  rabbitmq:
    username: admin
    password: nhnacademy123!
    host: 133.186.241.167
    port: 5672

logstash:
  host: 115.94.72.197
  port: 50000 # Logstash TCP input 포트


url: https://api-keymanager.nhncloudservice.com
appKey: qTQNj7LyHhdAazH3
keyId: f5e65a4f86194461bb3b6a01de675dcf

keyStoreFilePath: triple-seven.p12
password: nhn24





management:
  health:
    status:
      order: DOWN, UP
  endpoint:
    jolokia:
      enable: true
    pause:
      enabled: true
    resume:
      enabled: true
    web:
      exposure:
        include: health
  info:
    env:
      enabled: true

server:
  shutdown: graceful




aladin:
  api:
    key: ttbrlgus45311101001





