server:
  port: 8086


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

eureka:
  instance:
    instance-id: book-coupon-api-1
    hostname: localhost