spring:

  profiles:
    active: dev
  rabbitmq:
    username: admin
    password: nhnacademy123!
    host: 133.186.241.167
    port: 5672
    listener:
      simple:
        acknowledge-mode: MANUAL
        prefetch: 10 # 한 번에 가져올 메시지 수를 제한
        concurrency: 2 # 동시 실행 소비자 수 제한
        max-concurrency: 5 # 최대 동시 실행 소비자 수
        declare: false # 큐 재선언 비활성화


  lifecycle:
    timeout-per-shutdown-phase: 30s

  application:
    name: book-coupon-api
  cloud:
    loadbalancer:
      retry:
        enabled: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  elasticsearch:
    uris: http://115.94.72.197:9200
    username: elastic
    password: nhnacademy123!

eureka:
  instance:
    health-check-url: /actuator/health
    instance-id: book-coupon-api
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

url: https://api-keymanager.nhncloudservice.com
appKey: qTQNj7LyHhdAazH3
keyId: f5e65a4f86194461bb3b6a01de675dcf


management:
  health:
    status:
      order: DOWN, UP
  endpoint:
    jolokia:
      enable: true
    pause:
      enabled: true
    resume:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true

server:
  shutdown: graceful

aladin:
  api:
    key: ttbrlgus45311101001

logging:
  level:
    root: info
  logstash:
    host: 115.94.72.197
    port: 50000 # Logstash TCP input 포트


hibernate:
  dialect: org.hibernate.dialect.MySQLDialect


object:
  storage:
    url: https://kr1-api-object-storage.nhncloudservice.com/v1/AUTH_c20e3b10d61749a2a52346ed0261d79e
  auth:
    url: https://api-identity.infrastructure.cloud.toast.com/v2.0/tokens
  tenantId: c20e3b10d61749a2a52346ed0261d79e
  username: rlgus4531@naver.com
  password: team3