# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI/CD Pipeline for Spring Boot BookCoupon Api
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven



      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Build Docker image
        run: |
          docker build -t lushlife99/nhn-book-coupon:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Remove unused Docker images
        run: |
          docker image prune -a --filter "until=72h"

      - name: Push Docker image
        run: |
          docker push lushlife99/nhn-book-coupon:${{ github.sha }}

      - name: Set P12 file as environment variable
        run: |
          echo "${{ secrets.P12_FILE }}" | base64 --decode > p12_encoded_file
          P12_FILE_CONTENT=$(cat p12_encoded_file | base64 -w 0)
          echo "P12_FILE=$P12_FILE_CONTENT" >> $GITHUB_ENV
          rm p12_encoded_file



  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to First Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull lushlife99/nhn-book-coupon:${{ github.sha }}
            if [ "$(docker ps -aq --filter "name=book-coupon-api-instance-1")" ]; then
              docker stop book-coupon-api-instance-1 || true
              docker rm -f book-coupon-api-instance-1 || true
            fi
            docker run --name book-coupon-api-instance-1 \
            --network nhn-book-store-network \
            -p 8086:8086 \
            -e SPRING_PROFILES_ACTIVE=instance1 \
            -e P12_FILE_PATH=$GITHUB_WORKSPACE/secrets/triple-seven.p12 \
            -e P12_PASSWORD=${{ secrets.P12_PASSWORD }} \
            -d lushlife99/nhn-book-coupon:${{ github.sha }}


      - name: Check First Instance via Eureka
        run: |
          START_TIME=$(date +%s)
          while : ; do
            RESPONSE=$(curl -s -H "Accept: application/xml" http://${{ secrets.EUREKA_USERNAME }}:${{ secrets.EUREKA_PASSWORD }}@nhn24.store/eureka/eureka/instances/book-coupon-api-1)

            # 응답이 비어 있는지 확인
            if [ -z "$RESPONSE" ]; then
              echo "Error: Empty response from Eureka server."
              exit 1
            fi

            # XML 파싱을 위해 xmllint 사용
            STATUS=$(echo "$RESPONSE" | xmllint --xpath "string(//status)" - 2>/dev/null)

            # xmllint 파싱이 실패하면 오류 처리
            if [ $? -ne 0 ]; then
              echo "Error: Failed to parse XML response."
              echo "Response received: $RESPONSE"
              exit 1
            fi

            # 상태가 "UP"이면 종료
            if [ "$STATUS" == "UP" ]; then
              echo "First instance is healthy and UP."
              break
            fi

            # 180초 경과 체크
            CURRENT_TIME=$(date +%s)
            ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
            if [ $ELAPSED_TIME -ge 180 ]; then
              echo "First instance is not healthy within 3 minutes. Aborting deployment."
              exit 1
            fi

            # 10초 대기 후 재시도
            sleep 10
          done
            

      - name: Deploy to Second Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_ID }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            if [ "$(docker ps -aq --filter "name=book-coupon-api-instance-2")" ]; then
              docker stop book-coupon-api-instance-2 || true
              docker rm -f book-coupon-api-instance-2 || true
            fi
            docker run --name book-coupon-api-instance-2 
              --network nhn-book-store-network \
              -p 8087:8087 \
              -e SPRING_PROFILES_ACTIVE=instance2 \
              -e P12_FILE_PATH=$GITHUB_WORKSPACE/secrets/triple-seven.p12 \
              -e P12_PASSWORD=${{ secrets.P12_PASSWORD }} \
              -d lushlife99/nhn-book-coupon:${{ github.sha }}

      - name: Check Second Instance via Eureka
        run: |
          START_TIME=$(date +%s)
          while : ; do
            RESPONSE=$(curl -s -H "Accept: application/xml" http://${{ secrets.EUREKA_USERNAME }}:${{ secrets.EUREKA_PASSWORD }}@nhn24.store/eureka/eureka/instances/book-coupon-api-2)
          
            # 응답이 비어 있는지 확인
            if [ -z "$RESPONSE" ]; then
              echo "Error: Empty response from Eureka server."
              exit 1
            fi
          
            # XML 파싱을 위해 xmllint 사용
            STATUS=$(echo "$RESPONSE" | xmllint --xpath "string(//status)" - 2>/dev/null)
          
            # xmllint 파싱이 실패하면 오류 처리
            if [ $? -ne 0 ]; then
              echo "Error: Failed to parse XML response."
              echo "Response received: $RESPONSE"
              exit 1
            fi
          
            # 상태가 "UP"이면 종료
            if [ "$STATUS" == "UP" ]; then
              echo "Second instance is healthy and UP."
              break
            fi
          
            # 180초 경과 체크
            CURRENT_TIME=$(date +%s)
            ELAPSED_TIME=$((CURRENT_TIME - START_TIME))
            if [ $ELAPSED_TIME -ge 180 ]; then
              echo "Second instance is not healthy within 3 minutes. Aborting deployment."
              exit 1
            fi
          
            # 10초 대기 후 재시도
            sleep 10
          done