name: CI/CD Pipeline for Spring Boot Book Api

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run SonarQube analysis
        run: |
          mvn clean verify sonar:sonar \
          -Dsonar.projectKey=tripleseven-book-coupon-api \
          -Dsonar.projectName=‘tripleseven-book-coupon-api’ \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}